### ISSUE TITLE
compiling on clang / osx

### ISSUE THREAD

**Issue by kylemcdonald** [teemupitkanen/mrpt#6]
to compile on osx i had to:

```
$ brew install gcc
$ CC=/usr/local/bin/gcc-6 CXX=/usr/local/bin/g++-6 pip install git+https://github.com/teemupitkanen/mrpt/
```

when i tried to install without gcc, first i had the problem of: `WARNING: '.' not a valid package name; please use only .-separated package names in setup.py` (strange).

i changed the setup.py import to add `from setuptools import setup, find_packages` and changed packages value to `packages=find_packages(),`. 

next `clang: error: unsupported option '-fopenmp'` so i removed the `-fopenmp` flag.

next:

```
cpp/Mrpt.h:139:27: error: variable length array of non-POD element type 'Gap'
            Gap found_branches[n_trees * depth];
```

that's when i switched to gcc.

**Comment by ejaasaari** [comment]
On linux compiling on clang seems to work fine. However, I pushed a commit that should fix the last error (the priority queue was unneccessary) if you want to try again.

For OpenMP you would need clang-omp: https://clang-omp.github.io/
Perhaps this should be mentioned in the ReadMe.

**Comment by kylemcdonald** [comment]
the above solution (using gcc) still works for me. but other approaches have problems.

```
$ git clone https://github.com/teemupitkanen/mrpt.git ; cd mrpt
Cloning into 'mrpt'...
remote: Counting objects: 1770, done.
remote: Total 1770 (delta 0), reused 0 (delta 0), pack-reused 1770
Receiving objects: 100% (1770/1770), 6.76 MiB | 1.34 MiB/s, done.
Resolving deltas: 100% (988/988), done.
```

first, compiling with built-in llvm:

```
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
$ pip install .
Processing /Users/kyle/Desktop/mrpt
Installing collected packages: mrpt
  Running setup.py install for mrpt ... error
    Complete output from command /usr/local/opt/python/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/g3/khw365m97xvfqf25cff_sqnr0000gn/T/pip-FmtOnV-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/g3/khw365m97xvfqf25cff_sqnr0000gn/T/pip-V5jqUj-record/install-record.txt --single-version-externally-managed --compile:
    WARNING: '.' not a valid package name; please use only .-separated package names in setup.py
    running install
    running build
    running build_py
    package init file '__init__.py' not found (or not a regular file)
    creating build
    creating build/lib.macosx-10.11-x86_64-2.7
    copying demo.py -> build/lib.macosx-10.11-x86_64-2.7
    copying mrpt.py -> build/lib.macosx-10.11-x86_64-2.7
    copying setup.py -> build/lib.macosx-10.11-x86_64-2.7
    running build_ext
    building 'mrptlib' extension
    creating build/temp.macosx-10.11-x86_64-2.7
    creating build/temp.macosx-10.11-x86_64-2.7/cpp
    clang -fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Icpp/lib -I/usr/local/lib/python2.7/site-packages/numpy/core/include -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c cpp/mrptmodule.cpp -o build/temp.macosx-10.11-x86_64-2.7/cpp/mrptmodule.o -std=c++11 -O3 -march=native -ffast-math -s -fno-rtti -fopenmp -DNDEBUG
    clang: error: unsupported option '-fopenmp'
    error: command 'clang' failed with exit status 1
    
    ----------------------------------------
Command "/usr/local/opt/python/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/g3/khw365m97xvfqf25cff_sqnr0000gn/T/pip-FmtOnV-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/g3/khw365m97xvfqf25cff_sqnr0000gn/T/pip-V5jqUj-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/g3/khw365m97xvfqf25cff_sqnr0000gn/T/pip-FmtOnV-build/
```

this won't work because of `clang: error: unsupported option '-fopenmp'`.

next, trying with clang-omp (now integrated into llvm):

```
$ brew install llvm
...
$ /usr/local/opt/llvm/bin/clang++ --version
clang version 4.0.0 (tags/RELEASE_400/final)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin
$ CC=/usr/local/opt/llvm/bin/clang CXX=/usr/local/opt/llvm/bin/clang++ pip install .
Processing /Users/kyle/Desktop/mrpt
Installing collected packages: mrpt
  Running setup.py install for mrpt ... error
    Complete output from command /usr/local/opt/python/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/g3/khw365m97xvfqf25cff_sqnr0000gn/T/pip-TeLFIc-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/g3/khw365m97xvfqf25cff_sqnr0000gn/T/pip-fiwNT5-record/install-record.txt --single-version-externally-managed --compile:
    WARNING: '.' not a valid package name; please use only .-separated package names in setup.py
    running install
    running build
    running build_py
    package init file '__init__.py' not found (or not a regular file)
    creating build
    creating build/lib.macosx-10.11-x86_64-2.7
    copying demo.py -> build/lib.macosx-10.11-x86_64-2.7
    copying mrpt.py -> build/lib.macosx-10.11-x86_64-2.7
    copying setup.py -> build/lib.macosx-10.11-x86_64-2.7
    running build_ext
    building 'mrptlib' extension
    creating build/temp.macosx-10.11-x86_64-2.7
    creating build/temp.macosx-10.11-x86_64-2.7/cpp
    /usr/local/opt/llvm/bin/clang -fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Icpp/lib -I/usr/local/lib/python2.7/site-packages/numpy/core/include -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c cpp/mrptmodule.cpp -o build/temp.macosx-10.11-x86_64-2.7/cpp/mrptmodule.o -std=c++11 -O3 -march=native -ffast-math -s -fno-rtti -fopenmp -DNDEBUG
    clang-4.0: warning: argument unused during compilation: '-s' [-Wunused-command-line-argument]
    In file included from cpp/mrptmodule.cpp:25:
    In file included from /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4:
    In file included from /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18:
    In file included from /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1788:
    /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
    #warning "Using deprecated NumPy API, disable it by " \
     ^
    1 warning generated.
    /usr/local/opt/llvm/bin/clang++ -bundle -undefined dynamic_lookup build/temp.macosx-10.11-x86_64-2.7/cpp/mrptmodule.o -L/usr/local/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/sqlite/lib -lstdc++ -o build/lib.macosx-10.11-x86_64-2.7/mrptlib.so -lgomp
    ld: library not found for -lgomp
    clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
    error: command '/usr/local/opt/llvm/bin/clang++' failed with exit status 1
    
    ----------------------------------------
Command "/usr/local/opt/python/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/g3/khw365m97xvfqf25cff_sqnr0000gn/T/pip-TeLFIc-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/g3/khw365m97xvfqf25cff_sqnr0000gn/T/pip-fiwNT5-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/g3/khw365m97xvfqf25cff_sqnr0000gn/T/pip-TeLFIc-build/
```

problem seems to be `library not found for -lgomp`. so i add `'-L/usr/local/opt/llvm/lib'` to `extra_link_args` in setup.py, and run again:

```
$ CC=/usr/local/opt/llvm/bin/clang CXX=/usr/local/opt/llvm/bin/clang++ pip install .
$ python -c "import mrpt"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "mrpt.py", line 9, in <module>
    import mrptlib
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/mrptlib.so, 2): Library not loaded: @rpath/libomp.dylib
  Referenced from: /usr/local/lib/python2.7/site-packages/mrptlib.so
  Reason: image not found
```

but that's just because python doesn't know where to find openmp. so i add it to my path:

```
$ LD_LIBRARY_PATH=/usr/local/opt/llvm/lib/ python -c "import mrpt"
```

then that finally works.

alternatively, using gcc:

```
$ pip uninstall mrpt # remove installed mrpt
$ git checkout -- . # remove any changes to setup.py
$ CC=/usr/local/bin/gcc-6 CXX=/usr/local/bin/g++-6 pip install .
Processing /Users/kyle/Desktop/mrpt
Installing collected packages: mrpt
  Running setup.py install for mrpt ... done
Successfully installed mrpt-0.1
$ python -c "import mrpt"
```

this is successful immediately, without changes to setup.py, and without adding any libraries to my path. looking at the .so it looks like:

```
$ otool -L /usr/local/lib/python2.7/site-packages/mrptlib.so
/usr/local/lib/python2.7/site-packages/mrptlib.so:
	/usr/local/opt/gcc/lib/gcc/6/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.22.0)
	/usr/local/opt/gcc/lib/gcc/6/libgomp.1.dylib (compatibility version 2.0.0, current version 2.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	/usr/local/lib/gcc/6/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```

gcc hard linked to the dylib instead of using the rpath.

hope that's helpful. ideally the next official llvm from apple support openmp and this will be more straightforward :)

**Comment by ejaasaari** [comment]
Thanks, I pushed a commit that adds the extra_links_args and mentions LLVM installation in the README. This seemed to be all that I needed to get it working on MacOS (didn't have to modify LD_LIBRARY_PATH).
